
const I18N={
 en:{brand:'Arithuyil Arivom',heroEyebrow:'Pournami Dhyanam',heroTitle:'Pournami Meditation for Mind & Inner Relaxation',heroDesc:'A guided meditation experience designed to create a calm space for reflection, relaxation and focused practice.',details:'Program Details',detailsSub:'Understand the program before you book.',why:'Why Pournami Dhyanam?',benefits:'Program Benefits',testimonials:'Participant Experiences',offerTitle:'Choose Your Booking',offerSub:'Launch pricing is controlled by the Admin and may change for future programs.',online:'Online • Zoom',offline:'Live at Adambakkam Centre',book:'Book Now',regular:'Regular Price',filled:'slots filled',completed:'Offer Completed',login:'Member Login',dashboard:'Dashboard',contact:'Contact',see:'See More Details',name:'Name',mobile:'Mobile Number',save:'Continue',loginBtn:'Login',password:'Password',logout:'Logout',upcoming:'Upcoming Program',current:'Current Program',feedback:'Feedback',submit:'Submit Feedback',rating:'Rating',experience:'Your Experience',map:'View Location',zoom:'Join Zoom Class',payment:'Continue to Payment',close:'Close',loginHint:'Your account is created after successful payment.',offerStarts:'Offer Starts From',registrationOpen:'Registration is Open',comingSoon:'Coming Soon',timer:'Offer Timer',processing:'Processing...',paymentSuccess:'Payment successful. Your booking is confirmed.',paymentFailed:'Payment could not be completed.',required:'Please fill all required fields.',invalidMobile:'Enter a valid 10-digit mobile number.',leadSaved:'Your details are saved. Welcome to the program details.',nextMonth:'Next month registration',noAccess:'This program is not currently open for booking.'},
 ta:{brand:'அறிதுயில் அறிவோம்',heroEyebrow:'பௌர்ணமி தியானம்',heroTitle:'மனம் மற்றும் உள்ளார்ந்த அமைதிக்கான பௌர்ணமி தியானம்',heroDesc:'மனம் தளர்வு, அமைதி மற்றும் கவனத்தை வளர்க்க வழிகாட்டப்படும் சிறப்பு தியான அனுபவம்.',details:'நிகழ்ச்சி விவரங்கள்',detailsSub:'பதிவு செய்வதற்கு முன் நிகழ்ச்சியை முழுமையாக அறிந்து கொள்ளுங்கள்.',why:'பௌர்ணமி தியானம் ஏன்?',benefits:'நிகழ்ச்சியின் சிறப்புகள்',testimonials:'பங்கேற்பாளர்களின் அனுபவங்கள்',offerTitle:'பதிவு விருப்பத்தை தேர்வு செய்யுங்கள்',offerSub:'Launch offer-ஐ Admin நிர்ணயிக்கிறார்; எதிர்கால நிகழ்ச்சிகளில் விலை மாறலாம்.',online:'ஆன்லைன் • Zoom',offline:'Adambakkam Centre-ல் நேரடி வகுப்பு',book:'பதிவு செய்யுங்கள்',regular:'வழக்கமான விலை',filled:'இடங்கள் நிரம்பியுள்ளன',completed:'Offer முடிந்தது',login:'Member Login',dashboard:'Dashboard',contact:'தொடர்பு',see:'மேலும் விவரங்கள்',name:'பெயர்',mobile:'மொபைல் எண்',save:'தொடரவும்',loginBtn:'Login',password:'கடவுச்சொல்',logout:'Logout',upcoming:'வரவிருக்கும் நிகழ்ச்சி',current:'தற்போதைய நிகழ்ச்சி',feedback:'கருத்து',submit:'கருத்தை சமர்ப்பிக்கவும்',rating:'மதிப்பீடு',experience:'உங்கள் அனுபவம்',map:'இருப்பிடத்தை பார்க்க',zoom:'Zoom வகுப்பில் சேர',payment:'Payment-க்கு தொடரவும்',close:'மூடு',loginHint:'Payment வெற்றிகரமாக முடிந்த பிறகு உங்கள் account உருவாக்கப்படும்.',offerStarts:'Offer தொடங்கும் நேரம்',registrationOpen:'பதிவு தற்போது திறக்கப்பட்டுள்ளது',comingSoon:'விரைவில் திறக்கப்படும்',timer:'Offer Timer',processing:'செயலாக்கப்படுகிறது...',paymentSuccess:'Payment வெற்றிகரமாக முடிந்தது. உங்கள் booking உறுதி செய்யப்பட்டது.',paymentFailed:'Payment முடிக்கப்படவில்லை.',required:'தேவையான அனைத்து விவரங்களையும் நிரப்புங்கள்.',invalidMobile:'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடுங்கள்.',leadSaved:'உங்கள் விவரங்கள் சேமிக்கப்பட்டன. நிகழ்ச்சி விவரங்களை பார்க்கலாம்.',nextMonth:'அடுத்த மாத பதிவு',noAccess:'இந்த நிகழ்ச்சிக்கான பதிவு தற்போது திறக்கப்படவில்லை.'}
};
let currentLang=localStorage.getItem('aa_meditation_lang')||'en';
function t(k){return (I18N[currentLang]||I18N.en)[k]||k}
function setLang(lang){currentLang=lang;localStorage.setItem('aa_meditation_lang',lang);document.documentElement.lang=lang==='ta'?'ta':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));if(window.renderDynamic)window.renderDynamic()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(b)setLang(b.dataset.lang)});
